### PR TITLE
Javadoc correction test

### PR DESCRIPTION
**Pull request by amschwartz**
Some javadoc corrections.
Also adding a new header, ecsPaymentId.

### CODE REVIEW

**Comment by nmengin** [comment]
Ok for the corrections but I don't know if the travis problems will be resolved.
We are going to see it soon when we release the version.

**Comment by profesorfalken** [comment]
Ok it seems better. 
I do not know why we have empy javadocs in the implementation class but.. anyway, we are going to see if now the process works.

**Comment by profesorfalken** [comment]
Still lots of javadoc errors... but the artifact is well published on Sonatype repository: 

https://oss.sonatype.org/content/repositories/snapshots/eu/payzen/sdk/payzen-ws-sdk/1.0.3-SNAPSHOT/

**Comment by nmengin** [comment]
The problems is only for the RELEASE versions.
Errors have to be fixed in the way to RELEASE the module.

**Pull request merged**
